### ISSUE TITLE
Add a Plonky3 version pin

### ISSUE THREAD

**Issue by morganthomas** [valida-xyz/valida#119]
Specify a commit hash for Plonky3 in the build files which lets Valida be built without having a local clone of Plonky3.

**Comment by morganthomas** [comment]
Question: what if someone wants to build Valida with a local clone of Plonky3? What would they have to do?

**Comment by dlubarov** [comment]
Since Plonky3 deps are currently path dependencies, I think building against a local clone should be the default behavior?

We should probably start versioning Plonky3 some time soon though, so that changes don't automatically break users of it. After that I think cargo's [patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) feature could be used to switch to a local clone, at least in principle (I've had some issues with it in the past).

**Comment by morganthomas** [comment]
Who benefits from building against a local clone as the default behavior, and how? Having this as the default behavior violates the reproducibility of builds and uniform build procedures that users of `cargo` expect. From [The Cargo Book, section "Why Cargo Exists"](https://doc.rust-lang.org/cargo/guide/why-cargo-exists.html):

> Cargo is the Rust package manager. It is a tool that allows Rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) to declare their various dependencies and ensure that you’ll always get a repeatable build.
> To accomplish this goal, Cargo does four things:
>
> * Introduces two metadata files with various bits of package information.
> * Fetches and builds your package’s dependencies.
> * Invokes rustc or another build tool with the correct parameters to build your package.
> * Introduces conventions to make working with Rust packages easier.
> To a large extent, Cargo normalizes the commands needed to build a given program or library; this is one aspect to the above mentioned conventions. As we show later, the same command can be used to build different [artifacts](https://doc.rust-lang.org/cargo/appendix/glossary.html#artifact), regardless of their names. Rather than invoke rustc directly, we can instead invoke something generic such as cargo build and let cargo worry about constructing the correct rustc invocation. Furthermore, Cargo will automatically fetch from a [registry](https://doc.rust-lang.org/cargo/appendix/glossary.html#registry) any dependencies we have defined for our artifact, and arrange for them to be incorporated into our build as needed.
> It is only a slight exaggeration to say that once you know how to build one Cargo-based project, you know how to build all of them.

Currently, the problem with introducing a version pin is that Plonky3 is referenced in so many places, and it is hard coded in each of these places to be a local clone at a fixed relative path. In my mind, what would make sense would be for a version pin of Plonky3 to be introduced in one place, such that it would only need to be changed in one place later, when the version changes. What would also make sense to me would be to have a build flag to use a local clone, or at least a way to easily modify a build file to use a local clone.

I don't think that for most users of this code, their purposes would be better served by having Plonky3 be a local clone by default. I think for most users of this code, their purposes would be better served by having a pinned version of Plonky3 by default, and being able to run `cargo build` on this repo and have that just work, reproducibly, regardless of whether there's a local clone of Plonky3 or not.
