### ISSUE TITLE
Consistency of permutation argument traces with each other

### ISSUE THREAD

**Issue by morganthomas** [valida-xyz/valida#128]
In Valida, there is one permutation argument per chip. The permutation argument for a chip checks all of the interactions which that chip participates in. It checks that the sends and receives of those interactions are in a one-to-one correspondence, and it checks the consistency of the permutation argument trace with the main trace for that chip. That all happens in Interaction<F>::eval_permutation_constraints, defined here:

https://github.com/valida-xyz/valida/blob/main/machine/src/chip.rs#L210

This permutation argument checks the consistency of the permutation trace with the main trace of the chip this permutation argument is for. It does not, however, (directly, explicitly, in this section of code) check the consistency of the permutation trace with the main traces of any of the other chips that take part in the interactions.

Does this suffice? What needs to be shown is that for any interaction, the respective permutation traces for the two chips in that interaction each need to contain the same sends and receives for that interaction. In other words, we need to show that the permutation arguments for two chips in an interaction don't make two individually consistent yet jointly inconsistent sets of claims about the sends and receives that exist in that interaction.

**Comment by morganthomas** [comment]
Seems to me an obvious way to solve this problem (if there is a problem) would be to use variable sharing: to construct the permutation constraints for different chips in such a way that because they share the same variables, the permutation traces satisfying those constraints must contain the same sends and receives for the same interactions. 

What's not so clear to me is that we can use variable sharing in this context, considering that the separate permutation arguments for a chip are separate STARK arguments, which are batch-verified using a batch multi-opening proof.

Perhaps it would make more sense to use one permutation argument for all chips and all interactions, instead of one permutation argument per chip?

**Comment by dlubarov** [comment]
In [here](https://github.com/valida-xyz/valida/blob/main/derive/src/lib.rs#L598) we check that the cumulative sums from each chip cancel out to zero. That should have the effect of enforcing that the overalls multiset of sends and receives (considering all chips' traces) match one another.

**Comment by morganthomas** [comment]
Thanks for the reply, Daniel! Okay, so the way I'm understanding this now is that each chip can have a non-zero cumulative sum for its permutation argument. The way I understood this before was that each permutation argument would individually have a cumulative sum of zero. This was under the assumption that the corresponding receives for the sends from a chip would be in that chip's permutation trace, and vice versa for the sends for its receives. Now I'm understanding that each permutation argument trace contains only one side of a corresponding send/receive pair. As a result, they should each have non-zero cumulative sums, and the sum of those cumulative sums should be zero.

**Comment by morganthomas** [comment]
Closing this as a non-issue.
