### ISSUE TITLE
Writing to an arbitrary RAM address

### ISSUE THREAD

**Issue by morganthomas** [valida-xyz/valida#81]
`Load32` provides the ability to load from an arbitrary RAM address. `Store32` should provide the ability to write to an arbitrary RAM address. As [specified](https://github.com/valida-xyz/valida-compiler/issues/2) and implemented, it does not. Instead of acting as the write-side analogue of `Load32`, `Store32` acts as an analogue of `LW`; it moves a value from one stack location to another stack location, with the stack locations determined as fixed offsets from `fp`. What's needed is an instruction to write to a RAM address specified at a location on the stack.

**Comment by dlubarov** [comment]
Done in #82 (the change was merged as part of #90)
